config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  resources :fighters, only: [:index, :new, :create, :edit, :update, :destroy] do
  end

  resources :fights, only: [:index, :show, :new, :create] do
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fight.rb
class Fight < ApplicationRecord
  belongs_to :player, class_name: "Fighter", optional: true
  belongs_to :opponent, class_name: "Fighter", optional: true

  belongs_to :player_weapon, class_name: "Weapon", optional: true
  belongs_to :opponent_weapon, class_name: "Weapon", optional: true

  validates :player, presence: true
  validates :opponent, presence: true
  validates :player_weapon, presence: true
  validates :opponent_weapon, presence: true
end

app/models/fighter.rb
class Fighter < ApplicationRecord
  mount_uploader :photo, PhotoUploader

  # has_many :fights, dependent: :destroy
  # Wrong DB Scheme, can't find Fighter as player or opponent

  # PG::UndefinedColumn: ERROR: column fights.fighter_id does not exist LINE 1:
  # SELECT "fights".* FROM "fights" WHERE "fights"."fighter_id" ... ^ :
  # SELECT "fights".* FROM "fights" WHERE "fights"."fighter_id" = $1

  validates :name, presence: true, uniqueness: true, length: { maximum: 15 }
  validates :health, presence: true, inclusion: { in: (100..150), message: "must be between 100 and 150" }
  validates :power, presence: true, inclusion: { in: (10..20), message: "must be between 10 and 20" }
  validates :luck, presence: true
end

app/models/weapon.rb
class Weapon < ApplicationRecord
  belongs_to :fight, optional: true

  validates :name, presence: true
  validates :attack, presence: true
  validates :defense, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/fighters_controller.rb
class FightersController < ApplicationController
  def index
    @fighters = Fighter.all
  end

  def new
    @fighter = Fighter.new
  end

  def create
    @fighter = Fighter.new(fighter_params)
    @fighter.luck = rand(1.0..2.5)
    @fighter.name = @fighter.name.downcase.capitalize
    if @fighter.save
      redirect_to fighters_path
    else
      render :new
    end
  end

  def edit
    @fighter = Fighter.find(params[:id])
  end

  def update
    @fighter = Fighter.find(params[:id])
    @fighter.update(fighter_params)
    if @fighter.save
      redirect_to fighters_path
    else
      render :edit
    end
  end

  def destroy
    @fighter = Fighter.find(params[:id])
    @player_history = Fight.where(player_id: params[:id])
    @player_history.destroy_all
    @opponent_history = Fight.where(opponent_id: params[:id])
    @opponent_history.destroy_all
    @fighter.destroy
    redirect_to fighters_path
  end

  private

  def fighter_params
    params.require(:fighter).permit(:name, :health, :power, :photo, :luck)
  end
end

app/controllers/fights_controller.rb
class FightsController < ApplicationController
  def index
    @fights = Fight.all
  end

  def show
    @fight = Fight.find(params[:id])
    @player = @fight.player
    @opponent = @fight.opponent
    @player_turns = @fight.player_turns
    @opponent_turns = @fight.opponent_turns

    if @player_turns.empty?
      until @player_turns.sum >= @opponent.health || @opponent_turns.sum >= @player.health
        p_damage = ((@player.power + @fight.player_weapon.attack) * rand(1.0..@player.luck)).round
        o_resilience = (@fight.opponent_weapon.defense * rand(1.0..@player.luck)).round
        if o_resilience >= p_damage
          @player_turns << 0
        else
          @player_turns << (p_damage - o_resilience)
        end
        break if @player_turns.sum >= @opponent.health

        o_damage = ((@opponent.power + @fight.opponent_weapon.attack) * rand(1.0..@opponent.luck)).round
        p_resilience = (@fight.player_weapon.defense * rand(1.0..@player.luck)).round
        if p_resilience >= o_damage
          @opponent_turns << 0
        else
          @opponent_turns << (o_damage - p_resilience)
        end
      end

      @player.match_count += 1
      @opponent.match_count += 1
      (@opponent.health - @player_turns.sum).positive? ? @opponent.win += 1 : @player.win += 1
      @player.save
      @opponent.save
      @fight.save
    end

    (@opponent.health - @player_turns.sum).positive? ? @winner = @opponent : @winner = @player
  end

  def new
    @fight = Fight.new
    @fighters = Fighter.all
    @weapons = Weapon.all
  end

  def create
    # @fight = Fight.new(fight_params) doesn't work, type mismatch, expect id, receive integer or string
    @fight = Fight.new
    #fix simple_form bug when render :new
    @fighters = Fighter.all
    #fix simple_form bug when render :new
    @weapons = Weapon.all
    @fight.player = Fighter.find_by(id: fight_params[:player])
    @fight.player_weapon = Weapon.find_by(id: fight_params[:player_weapon])
    @fight.opponent = Fighter.find_by(id: fight_params[:opponent])
    @fight.opponent_weapon = Weapon.find_by(id: fight_params[:opponent_weapon])
    if @fight.save
      redirect_to fight_path(@fight)
    else
      render :new
    end
  end

  private

  def fight_params
    params.require(:fight).permit(:player, :opponent, :player_weapon, :opponent_weapon)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fighters_helper.rb
module FightersHelper
end

app/helpers/fights_helper.rb
module FightsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/fighters/edit.html.erb
<div class="container">
  <div class="border rounded mt-5 p-5 text-center">
    <div class="mb-5">
      <h1><i class="fas fa-skull-crossbones"></i> Modify your Fighter <i class="fas fa-skull-crossbones"></i></h1>
      <h4>Modify your fighter !</h4>
    </div>
    <%= simple_form_for [@fighter], url: fighter_path do |f| %>
    <%= f.input :name %>
    <%= f.input :health, collection: (100..150), default: 100 %>
    <%= f.input :power, collection: (10..20) %>
    <%= f.input :photo %>
    <%= f.submit "Update this fighter", class: "btn btn-success" %>
    <% end %>
  </div>
</div>

app/views/fighters/index.html.erb
<div class="container">
  <div class="border rounded mt-5 p-5 text-center">
    <h1><i class="fas fa-skull-crossbones"></i> Fighter List <i class="fas fa-skull-crossbones"></i></h1>
    <div class="d-flex flex-wrap justify-content-between">
      <% @fighters.each do |fighter| %>
      <div class="card mt-5" style="width: 18rem;">
        <div class="card-img-top" >
          <%= cl_image_tag fighter.photo, height: 300, width: 250, crop: :fill %>
        </div>
        <div class="card-body">
          <h5 class="card-title"><%= fighter.name %></h5>
          <p class="card-text">Health: <%= fighter.health %> <br>Power: <%= fighter.power %></p>
          <% if fighter.match_count == 0 %>
            <p class="card-text"> Winrate: No fight yet!</p>
          <% else %>
            <p class="card-text"> Winrate: <%= ((fighter.win).fdiv(fighter.match_count) * 100).round %> %</p>
          <% end %>
          <%= link_to edit_fighter_path(fighter) do %>
            <div class="btn btn-secondary mt-5">
              <i class="fas fa-tools"> Edit </i>
            </div>
          <% end %>
          <%= link_to fighter_path(fighter), method: :delete, data: { confirm: "Are you sure?" } do %>
            <div class="btn btn-secondary mt-5">
              <i class="fas fa-trash" aria-hidden="true"></i>
            </div>
          <% end %>
        </div>
      </div>
      <% end %>
    </div>
    <%= link_to new_fighter_path, style: 'color:#F4F4F4' do %>
      <div class="mt-5 btn btn-success"> New fighter </div>
    <% end %>
    <%= link_to new_fight_path, style: 'color:#F4F4F4' do %>
      <div class="mt-5 btn btn-danger"> New fight </div>
    <% end %>
  </div>
</div>

app/views/fighters/new.html.erb
<div class="container">
  <div class="border rounded mt-5 p-5 text-center">
    <div class="mb-5">
      <h1><i class="fas fa-skull-crossbones"></i> Champions Factory <i class="fas fa-skull-crossbones"></i></h1>
      <h4>Create your own fighter !</h4>
    </div>
    <%= simple_form_for [@fighter] do |f| %>
    <%= f.input :name %>
    <%= f.input :health, default: 100, collection: (100..150) %>
    <%= f.input :power, default: 10, collection: (10..20) %>
    <%= f.input :photo %>
    <%= f.submit "Create your fighter", class: "btn btn-success" %>
    <% end %>
  </div>
</div>

app/views/fights/index.html.erb
<div class="container">
  <div class="border rounded mt-5 p-5 text-center">
    <h1><i class="fas fa-skull-crossbones"></i> Fights history <i class="fas fa-skull-crossbones"></i></h1>
    <%= link_to new_fight_path do %>
      <div class="mt-5 btn btn-danger"> New Fight </div>
    <% end %>
    <div class="d-flex flex-wrap justify-content-between">
      <% @fights.each do |fight| %>
        <%= link_to fight_path(fight), style: 'color:#000000' do %>
          <div class="card mt-5" style="width: 18rem;">
            <div class="card-img-top" >
              <%= cl_image_tag fight.player.photo, height: 300, width: 250, crop: :fill %>
            </div>
            <div class="card-body">
              <h5 class="card-title"><%= fight.player.name %>
              VS <%= fight.opponent.name %>
              </h5>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/fights/new.html.erb
<div class="container">
  <div class="border rounded mt-5 p-5 text-center">
    <div class="mb-5">
      <h1><i class="fas fa-dumbbell"></i> Fighter Academy <i class="fas fa-dumbbell"></i></h1>
      <div class="mt-5">
        <h4>You can create your own champion !</h4>
      </div>
    </div>
    <%= link_to new_fighter_path do %>
    <div class="btn btn-success">Create a Fighter</div>
    <% end %>
  </div>
</div>
<div class="container">
  <div class="border rounded mt-5 p-5 text-center">
    <div class="mb-5">
      <h1><i class="fas fa-skull-crossbones"></i> Choose the two Opponents <i class="fas fa-skull-crossbones"></i></h1>
      <h4> Prepare to fight !</h4>
    </div>
    <%= simple_form_for [@fight] do |f| %>
    <div class="border rounded mt-5 p-5">
      <%= f.input :player, collection: @fighters, label: "Choose your fighter" %>
      <%= f.input :player_weapon, collection: @weapons, label: "Choose your weapon", default: @weapons.first %>
    </div>
    <div class="border rounded mt-5 p-5">
      <%= f.input :opponent, label: "Choose your opponent", collection: @fighters %>
      <%= f.input :opponent_weapon, collection: @weapons, label: "Choose Opponent weapon", default: @weapons.first %>
    </div>
    <%= f.submit "Fight", class: "btn btn-danger" %>
    <% end %>
  </div>
</div>

<div class="container">
  <div class="mt-5 p5 text-center">
    <%= link_to root_path do %>
      <div class="btn btn-secondary">Home</div>
    <% end %>
    <%= link_to fights_path do %>
      <div class="btn btn-secondary">Back</div>
    <% end %>
  </div>
</div>

app/views/fights/show.html.erb
<div class="container">
  <div class="border rounded mt-5 p-5 text-center">
    <div class="border rounded m-2 p-2">
      <h1><%= @fight.player.name %> VS <%= @fight.opponent.name %></h1>
    </div>
    <div>
      <ul class="list-unstyled text-left mt-5">
        <h2><%= @fight.player.name %> -
          <% if @fight.player_weapon.name == "Sword" %>
            <i class="fas fa-utensils"></i>
          <% elsif @fight.player_weapon.name == "Shield" %>
            <i class="fas fa-shield-alt"></i>
          <% else %>
            <i class="fas fa-fist-raised"></i>
          <% end %>
        </h2>
        <% @player_turns.each do |player_turn| %>
        <li>- <%= player_turn %> dmg</li>
        <% end %>
      </ul>
      <ul class="list-unstyled text-right  mt-5">
        <h2><%= @fight.opponent.name %> -
          <% if @fight.opponent_weapon.name == "Sword" %>
            <i class="fas fa-utensils"></i>
          <% elsif @fight.opponent_weapon.name == "Shield" %>
            <i class="fas fa-shield-alt"></i>
          <% else %>
            <i class="fas fa-fist-raised"></i>
          <% end %>
        </h2>
        <% @opponent_turns.each do |opponent_turn| %>
        <li>- <%= opponent_turn %> dmg</li>
        <% end %>
      </ul>
    </div>
    <div class="border rounded mt-5 p-3" >
      <h2><i class="fas fa-trophy"></i> Winner : <%= @winner.name %> !</h2>
    </div>
    <%= link_to fights_path do %>
      <div class="btn btn-secondary mt-5"> Return </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CaptainArena</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="d-flex flex-wrap justify-content-center bg-danger">
      <%= link_to root_path do %>
        <div class="border rounded m-1 p-2 btn btn-danger"> Home </div>
      <% end %>
      <%= link_to fights_path do %>
        <div class="border rounded m-1 p-2 btn btn-danger">Arena</div>
      <% end %>
      <%= link_to fighters_path do %>
        <div class="border rounded m-1 p-2 btn btn-danger">Fighters</div>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container">
  <div class="border rounded mt-5 p-5 text-center">
    <h1><i class="fas fa-skull-crossbones"></i> Captain Arena <i class="fas fa-skull-crossbones"></i></h1>
    <div class="mt-5">
      <h2>Who would win?</h2>
      <p>Create your fighter and let's find out!</p>
    </div>
    <%= link_to fights_path do %>
      <div class="btn btn-danger btn-lg mt-5"> Enter the Arena </div>
    <% end %>
  </div>
</div>